import { Suspense } from 'react'
import { Inter } from 'next/font/google'
import { NavigationProvider } from '../contexts/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavigationProvider>
        <Suspense>
          <body className={inter.className}>{children}</body>
        </Suspense>
      </NavigationProvider>
    </html>
  )
}
